# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: gmp-public
  name: frontend
  annotations:
    iam.gke.io/gcp-service-account: gmp-frontend@aiops-sentinel-16768.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gmp-public
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - arm64
                      - amd64
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      automountServiceAccountToken: true
      serviceAccountName: frontend
      containers:
        - args:
            - "--web.listen-address=:9090"
            - "--query.project-id=aiops-sentinel-16768"
          image: gke.gcr.io/prometheus-engine/frontend:v0.15.3-gke.0
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: web
          name: frontend
          ports:
            - containerPort: 9090
              name: web
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /-/ready
              port: web
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  namespace: gmp-public
  name: frontend
spec:
  clusterIP: None
  ports:
    - name: web
      port: 9090
  selector:
    app: frontend
